name: Main

permissions:
  contents: write

on: push

jobs:
  byukd:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v4
      - name: Build binaries
        run: |
          GOOS=windows GOARCH=amd64 go build -o nola.exe .
          GOOS=linux GOARCH=amd64 go build -o nola-linux-amd64 .
          GOOS=darwin GOARCH=arm64 go build -o nola-macos-arm64 .
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            nola.exe
            nola-linux-amd64
            nola-macos-arm64
